// Auto-generated structural Verilog from SPICE netlist
// Generated by spice2v.py (named-port-connection mode)

module adder_demo (
    A,
    B,
    S,
    clk,
    en,
    rst_n,
    VGND,
    VPWR
);
    inout A;
    inout B;
    inout S;
    inout clk;
    inout en;
    inout rst_n;
    inout VGND;
    inout VPWR;

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_36 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_36_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_47 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_47_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_14 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_15_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_25 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_25_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_4 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_4_A),
        .A0(sky130_fd_sc_hd__nor2_2_7_A),
        .X(sky130_fd_sc_hd__mux2_1_4_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_48 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_49_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_37 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_40_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_26 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_26_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_15 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_15_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_5 (
        .S(en),
        .A1(B),
        .A0(sky130_fd_sc_hd__or2_2_0_A),
        .X(sky130_fd_sc_hd__mux2_1_5_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_49 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_49_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_38 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_38_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_16 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_19_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_27 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_27_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_6 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_0_A),
        .A0(sky130_fd_sc_hd__xor2_2_4_A),
        .X(sky130_fd_sc_hd__mux2_1_6_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_39 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_39_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_28 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_32_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_17 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_18_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_7 (
        .S(en),
        .A1(sky130_fd_sc_hd__xor2_2_4_A),
        .A0(sky130_fd_sc_hd__or2_2_3_A),
        .X(sky130_fd_sc_hd__mux2_1_7_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_29 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_31_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_18 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_18_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_8 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_0_B),
        .A0(sky130_fd_sc_hd__xor2_2_4_B),
        .X(sky130_fd_sc_hd__mux2_1_8_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(sky130_fd_sc_hd__mux2_1_8_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_19 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_19_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_9 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_4_B),
        .A0(sky130_fd_sc_hd__nor2_2_7_B),
        .X(sky130_fd_sc_hd__mux2_1_9_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_0 (
        .Y(sky130_fd_sc_hd__and2_2_6_A),
        .A(sky130_fd_sc_hd__or2_2_0_A),
        .B(sky130_fd_sc_hd__or2_2_0_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a21bo_2 sky130_fd_sc_hd__a21bo_2_0 (
        .B1_N(sky130_fd_sc_hd__and2_2_1_B),
        .A2(sky130_fd_sc_hd__xor2_2_1_B),
        .X(sky130_fd_sc_hd__xor2_2_0_B),
        .A1(sky130_fd_sc_hd__xor2_2_1_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_0 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_2_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_1 (
        .Y(sky130_fd_sc_hd__and2_2_1_B),
        .A(sky130_fd_sc_hd__or2_2_3_A),
        .B(sky130_fd_sc_hd__or2_2_3_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_1 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_6_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_2 (
        .Y(sky130_fd_sc_hd__nand2_2_3_A),
        .A(sky130_fd_sc_hd__or2_2_4_A),
        .B(sky130_fd_sc_hd__or2_2_4_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a21boi_2 sky130_fd_sc_hd__a21boi_2_0 (
        .B1_N(sky130_fd_sc_hd__nand2_2_3_A),
        .A2(sky130_fd_sc_hd__a31o_2_3_X),
        .A1(sky130_fd_sc_hd__or2_2_4_X),
        .Y(sky130_fd_sc_hd__xnor2_2_1_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_2 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_2_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_10 (
        .Q(sky130_fd_sc_hd__or2_2_4_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_13_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_3 (
        .Y(sky130_fd_sc_hd__xnor2_2_2_A),
        .A(sky130_fd_sc_hd__nand2_2_3_A),
        .B(sky130_fd_sc_hd__or2_2_4_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_3 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_4_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_11 (
        .Q(sky130_fd_sc_hd__or2_2_0_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_12_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and3_2 sky130_fd_sc_hd__and3_2_0 (
        .B(sky130_fd_sc_hd__and3_2_0_B),
        .X(sky130_fd_sc_hd__and3_2_0_X),
        .A(sky130_fd_sc_hd__and3_2_0_A),
        .C(sky130_fd_sc_hd__and3_2_0_C),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_4 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_4_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_12 (
        .Q(sky130_fd_sc_hd__or2_2_3_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_10_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_5 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_5_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_13 (
        .Q(sky130_fd_sc_hd__or2_2_1_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_15_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_0 (
        .X(sky130_fd_sc_hd__xor2_2_0_X),
        .B(sky130_fd_sc_hd__xor2_2_0_B),
        .A(sky130_fd_sc_hd__xor2_2_0_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_6 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_6_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_14 (
        .Q(sky130_fd_sc_hd__nor2_2_1_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_14_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__o21bai_2 sky130_fd_sc_hd__o21bai_2_0 (
        .B1_N(sky130_fd_sc_hd__nor2_2_0_A),
        .Y(sky130_fd_sc_hd__and3_2_0_C),
        .A2(sky130_fd_sc_hd__xnor2_2_1_B),
        .A1(sky130_fd_sc_hd__nor2_2_7_Y),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_1 (
        .X(sky130_fd_sc_hd__xor2_2_1_X),
        .B(sky130_fd_sc_hd__xor2_2_1_B),
        .A(sky130_fd_sc_hd__xor2_2_1_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_7 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_8_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_15 (
        .Q(sky130_fd_sc_hd__or2_2_2_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_11_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_2 (
        .X(sky130_fd_sc_hd__xor2_2_2_X),
        .B(sky130_fd_sc_hd__xor2_2_2_B),
        .A(sky130_fd_sc_hd__xor2_2_2_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_8 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_8_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_10 (
        .S(en),
        .A1(sky130_fd_sc_hd__xor2_2_4_B),
        .A0(sky130_fd_sc_hd__or2_2_3_B),
        .X(sky130_fd_sc_hd__mux2_1_10_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_3 (
        .X(sky130_fd_sc_hd__xor2_2_3_X),
        .B(sky130_fd_sc_hd__xor2_2_3_B),
        .A(sky130_fd_sc_hd__xor2_2_3_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_9 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_9_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_11 (
        .S(en),
        .A1(sky130_fd_sc_hd__nor2_2_1_B),
        .A0(sky130_fd_sc_hd__or2_2_2_B),
        .X(sky130_fd_sc_hd__mux2_1_11_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_4 (
        .X(sky130_fd_sc_hd__xor2_2_4_X),
        .B(sky130_fd_sc_hd__xor2_2_4_B),
        .A(sky130_fd_sc_hd__xor2_2_4_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_12 (
        .S(en),
        .A1(A),
        .A0(sky130_fd_sc_hd__or2_2_0_B),
        .X(sky130_fd_sc_hd__mux2_1_12_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__clkbuf_16 sky130_fd_sc_hd__clkbuf_16_0 (
        .X(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .A(sky130_fd_sc_hd__clkbuf_16_2_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_13 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_2_B),
        .A0(sky130_fd_sc_hd__or2_2_4_B),
        .X(sky130_fd_sc_hd__mux2_1_13_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_0 (
        .Q(sky130_fd_sc_hd__nor2_2_1_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_3_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__clkbuf_16 sky130_fd_sc_hd__clkbuf_16_1 (
        .X(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .A(sky130_fd_sc_hd__clkbuf_16_2_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_14 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_1_B),
        .A0(sky130_fd_sc_hd__nor2_2_1_B),
        .X(sky130_fd_sc_hd__mux2_1_14_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_1 (
        .Q(sky130_fd_sc_hd__or2_2_0_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_5_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__clkbuf_16 sky130_fd_sc_hd__clkbuf_16_2 (
        .X(sky130_fd_sc_hd__clkbuf_16_2_X),
        .A(clk),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_15 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_3_B),
        .A0(sky130_fd_sc_hd__or2_2_1_B),
        .X(sky130_fd_sc_hd__mux2_1_15_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_0 (
        .B(sky130_fd_sc_hd__nor2_2_7_Y),
        .Y(sky130_fd_sc_hd__nor2_2_0_Y),
        .A(sky130_fd_sc_hd__nor2_2_0_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_2 (
        .Q(sky130_fd_sc_hd__or2_2_2_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_1_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_0 (
        .Y(sky130_fd_sc_hd__xnor2_2_0_Y),
        .A(sky130_fd_sc_hd__and2_2_6_A),
        .B(sky130_fd_sc_hd__xor2_2_4_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_1 (
        .B(sky130_fd_sc_hd__nor2_2_1_B),
        .Y(sky130_fd_sc_hd__nor2_2_4_B),
        .A(sky130_fd_sc_hd__nor2_2_1_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_0 (
        .A(sky130_fd_sc_hd__nor2_2_1_A),
        .X(sky130_fd_sc_hd__nor2_2_4_A),
        .B(sky130_fd_sc_hd__nor2_2_1_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_3 (
        .Q(sky130_fd_sc_hd__xor2_2_4_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_6_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_1 (
        .Y(sky130_fd_sc_hd__and3_2_0_B),
        .A(sky130_fd_sc_hd__nor2_2_0_Y),
        .B(sky130_fd_sc_hd__xnor2_2_1_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_2 (
        .B(sky130_fd_sc_hd__nor2_2_2_B),
        .Y(sky130_fd_sc_hd__xor2_2_0_A),
        .A(sky130_fd_sc_hd__nor2_2_6_Y),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_1 (
        .A(sky130_fd_sc_hd__or2_2_3_X),
        .X(sky130_fd_sc_hd__xor2_2_1_B),
        .B(sky130_fd_sc_hd__and2_2_1_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_4 (
        .Q(sky130_fd_sc_hd__or2_2_3_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_7_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_2 (
        .Y(sky130_fd_sc_hd__and3_2_0_A),
        .A(sky130_fd_sc_hd__xnor2_2_2_A),
        .B(sky130_fd_sc_hd__a31o_2_3_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_3 (
        .B(sky130_fd_sc_hd__nor2_2_3_B),
        .Y(sky130_fd_sc_hd__xor2_2_3_A),
        .A(sky130_fd_sc_hd__nor2_2_5_Y),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_2 (
        .A(sky130_fd_sc_hd__xor2_2_4_A),
        .X(sky130_fd_sc_hd__and2_2_2_X),
        .B(sky130_fd_sc_hd__xor2_2_4_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_5 (
        .Q(sky130_fd_sc_hd__nor2_2_7_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_4_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_4 (
        .B(sky130_fd_sc_hd__nor2_2_4_B),
        .Y(sky130_fd_sc_hd__xor2_2_2_A),
        .A(sky130_fd_sc_hd__nor2_2_4_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_3 (
        .A(sky130_fd_sc_hd__or2_2_1_A),
        .X(sky130_fd_sc_hd__nor2_2_2_B),
        .B(sky130_fd_sc_hd__or2_2_1_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_6 (
        .Q(sky130_fd_sc_hd__or2_2_1_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_0_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_5 (
        .B(sky130_fd_sc_hd__or2_2_2_B),
        .Y(sky130_fd_sc_hd__nor2_2_5_Y),
        .A(sky130_fd_sc_hd__or2_2_2_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(sky130_fd_sc_hd__nor2_2_5_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_4 (
        .A(sky130_fd_sc_hd__or2_2_2_A),
        .X(sky130_fd_sc_hd__nor2_2_3_B),
        .B(sky130_fd_sc_hd__or2_2_2_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__nor2_2_5_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_7 (
        .Q(sky130_fd_sc_hd__or2_2_4_A),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_2_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_7_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_0 (
        .X(sky130_fd_sc_hd__xor2_2_1_A),
        .B1(sky130_fd_sc_hd__and2_2_2_X),
        .A3(sky130_fd_sc_hd__xor2_2_4_X),
        .A1(sky130_fd_sc_hd__or2_2_0_A),
        .A2(sky130_fd_sc_hd__or2_2_0_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_0 (
        .B(sky130_fd_sc_hd__or2_2_0_B),
        .X(sky130_fd_sc_hd__or2_2_0_X),
        .A(sky130_fd_sc_hd__or2_2_0_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__or2_2_0_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_6 (
        .B(sky130_fd_sc_hd__or2_2_1_B),
        .Y(sky130_fd_sc_hd__nor2_2_6_Y),
        .A(sky130_fd_sc_hd__or2_2_1_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_50 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_53_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_5 (
        .A(sky130_fd_sc_hd__nor2_2_7_A),
        .X(sky130_fd_sc_hd__nor2_2_0_A),
        .B(sky130_fd_sc_hd__nor2_2_7_B),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_8 (
        .Q(sky130_fd_sc_hd__xor2_2_4_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_8_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_1 (
        .X(sky130_fd_sc_hd__xor2_2_2_B),
        .B1(sky130_fd_sc_hd__a31o_2_4_X),
        .A3(sky130_fd_sc_hd__xor2_2_0_A),
        .A1(sky130_fd_sc_hd__xor2_2_1_A),
        .A2(sky130_fd_sc_hd__xor2_2_1_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a21o_2 sky130_fd_sc_hd__a21o_2_0 (
        .X(sky130_fd_sc_hd__xor2_2_3_B),
        .B1(sky130_fd_sc_hd__nor2_2_4_A),
        .A1(sky130_fd_sc_hd__xor2_2_2_A),
        .A2(sky130_fd_sc_hd__xor2_2_2_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_1 (
        .B(sky130_fd_sc_hd__or2_2_1_B),
        .X(sky130_fd_sc_hd__or2_2_1_X),
        .A(sky130_fd_sc_hd__or2_2_1_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_7 (
        .B(sky130_fd_sc_hd__nor2_2_7_B),
        .Y(sky130_fd_sc_hd__nor2_2_7_Y),
        .A(sky130_fd_sc_hd__nor2_2_7_A),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_40 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_40_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_51 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_52_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_6 (
        .A(sky130_fd_sc_hd__and2_2_6_A),
        .X(sky130_fd_sc_hd__and2_2_6_X),
        .B(sky130_fd_sc_hd__or2_2_0_X),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_9 (
        .Q(sky130_fd_sc_hd__nor2_2_7_B),
        .RESET_B(rst_n),
        .D(sky130_fd_sc_hd__mux2_1_9_X),
        .CLK(sky130_fd_sc_hd__dfrtp_2_9_CLK),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_2 (
        .X(sky130_fd_sc_hd__a31o_2_2_X),
        .B1(sky130_fd_sc_hd__nor2_2_3_B),
        .A3(sky130_fd_sc_hd__or2_2_2_X),
        .A1(sky130_fd_sc_hd__nor2_2_1_A),
        .A2(sky130_fd_sc_hd__nor2_2_1_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and4bb_2 sky130_fd_sc_hd__and4bb_2_0 (
        .A_N(sky130_fd_sc_hd__xnor2_2_0_Y),
        .C(sky130_fd_sc_hd__and3_2_0_X),
        .B_N(sky130_fd_sc_hd__and2_2_6_X),
        .X(S),
        .D(sky130_fd_sc_hd__and4bb_2_1_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_2 (
        .B(sky130_fd_sc_hd__or2_2_2_B),
        .X(sky130_fd_sc_hd__or2_2_2_X),
        .A(sky130_fd_sc_hd__or2_2_2_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_52 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_52_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_41 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_41_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_30 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_41_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_3 (
        .X(sky130_fd_sc_hd__a31o_2_3_X),
        .B1(sky130_fd_sc_hd__a31o_2_2_X),
        .A3(sky130_fd_sc_hd__xor2_2_3_A),
        .A1(sky130_fd_sc_hd__xor2_2_2_A),
        .A2(sky130_fd_sc_hd__xor2_2_2_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__and4bb_2 sky130_fd_sc_hd__and4bb_2_1 (
        .A_N(sky130_fd_sc_hd__xor2_2_0_X),
        .C(sky130_fd_sc_hd__xor2_2_2_X),
        .B_N(sky130_fd_sc_hd__xor2_2_1_X),
        .X(sky130_fd_sc_hd__and4bb_2_1_X),
        .D(sky130_fd_sc_hd__xor2_2_3_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_3 (
        .B(sky130_fd_sc_hd__or2_2_3_B),
        .X(sky130_fd_sc_hd__or2_2_3_X),
        .A(sky130_fd_sc_hd__or2_2_3_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_53 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_53_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_42 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_47_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_31 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_31_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_20 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_27_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_4 (
        .X(sky130_fd_sc_hd__a31o_2_4_X),
        .B1(sky130_fd_sc_hd__nor2_2_2_B),
        .A3(sky130_fd_sc_hd__or2_2_1_X),
        .A1(sky130_fd_sc_hd__or2_2_3_A),
        .A2(sky130_fd_sc_hd__or2_2_3_B),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_4 (
        .B(sky130_fd_sc_hd__or2_2_4_B),
        .X(sky130_fd_sc_hd__or2_2_4_X),
        .A(sky130_fd_sc_hd__or2_2_4_A),
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_54 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_54_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_43 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_55_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_32 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_32_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_10 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_9_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_21 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_22_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_0 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_3_A),
        .A0(sky130_fd_sc_hd__or2_2_1_A),
        .X(sky130_fd_sc_hd__mux2_1_0_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(sky130_fd_sc_hd__mux2_1_0_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_55 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_55_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_44 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_45_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_33 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_57_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_22 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_22_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_11 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_12_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_1 (
        .S(en),
        .A1(sky130_fd_sc_hd__nor2_2_1_A),
        .A0(sky130_fd_sc_hd__or2_2_2_A),
        .X(sky130_fd_sc_hd__mux2_1_1_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_34 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_39_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_45 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_45_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_56 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_56_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_12 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_12_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_23 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_25_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_2 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_2_A),
        .A0(sky130_fd_sc_hd__or2_2_4_A),
        .X(sky130_fd_sc_hd__mux2_1_2_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_35 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_38_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_46 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_56_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_57 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_57_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_24 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_26_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__decap_3_13 (
        .VPWR(VPWR),
        .VGND(VGND),
        .VPB(sky130_fd_sc_hd__decap_3_5_VPB),
        .VNB(VGND)
    );

    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_3 (
        .S(en),
        .A1(sky130_fd_sc_hd__or2_2_1_A),
        .A0(sky130_fd_sc_hd__nor2_2_1_A),
        .X(sky130_fd_sc_hd__mux2_1_3_X),
        .VGND(VGND),
        .VPWR(VPWR),
        .VPB(VPWR),
        .VNB(VGND)
    );

endmodule // adder_demo

